# Generated by Django 5.2.13 on 2026-05-04 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20)),
                ('feeds_requested', models.PositiveIntegerField(default=0)),
                ('feeds_succeeded', models.PositiveIntegerField(default=0)),
                ('feeds_failed', models.PositiveIntegerField(default=0)),
                ('parser_version', models.CharField(default='rss-v1', max_length=50)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('etag', models.CharField(blank=True, max_length=500)),
                ('last_modified', models.CharField(blank=True, max_length=500)),
                ('last_status', models.PositiveIntegerField(blank=True, null=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_content_hash', models.CharField(blank=True, max_length=64)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='catalog.podcast')),
            ],
            options={
                'ordering': ['podcast__name', 'url'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('episode_url', models.URLField(blank=True)),
                ('enclosure_url', models.URLField(blank=True)),
                ('duration_raw', models.CharField(blank=True, max_length=100)),
                ('explicit', models.BooleanField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='catalog.podcast')),
            ],
            options={
                'ordering': ['-published_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('fetch', 'Fetch'), ('parse', 'Parse'), ('persist', 'Persist')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='catalog.feed')),
                ('scrape_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='catalog.scraperun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawFeedSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_uri', models.CharField(max_length=1000)),
                ('content_hash', models.CharField(max_length=64)),
                ('fetched_at', models.DateTimeField()),
                ('http_status', models.PositiveIntegerField()),
                ('etag', models.CharField(blank=True, max_length=500)),
                ('last_modified', models.CharField(blank=True, max_length=500)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='catalog.feed')),
                ('scrape_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_snapshots', to='catalog.scraperun')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('host', 'Host'), ('guest', 'Guest')], max_length=20)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('confidence', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='catalog.episode')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='catalog.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('episode', 'person', 'role'), name='unique_episode_person_role')],
            },
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['podcast', 'published_at'], name='catalog_epi_podcast_564a99_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['guid'], name='catalog_epi_guid_66acdc_idx'),
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('podcast', 'guid'), name='unique_episode_guid'),
        ),
        migrations.AddConstraint(
            model_name='rawfeedsnapshot',
            constraint=models.UniqueConstraint(fields=('feed', 'content_hash'), name='unique_raw_snapshot_per_feed_hash'),
        ),
    ]
