# Generated by Django 5.2.13 on 2026-05-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='parser_hint',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='podcast',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
