# Generated by Django 5.2.13 on 2026-05-04 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_feed_parser_hint_podcast_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('prompt_version', models.CharField(max_length=50)),
                ('provider', models.CharField(default='openai', max_length=50)),
                ('episodes_requested', models.PositiveIntegerField(default=0)),
                ('episodes_succeeded', models.PositiveIntegerField(default=0)),
                ('episodes_failed', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EpisodeGuestExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=20)),
                ('prompt_version', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('input_text', models.TextField()),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_extractions', to='catalog.episode')),
                ('extraction_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_extractions', to='catalog.extractionrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('confidence', models.FloatField(default=0)),
                ('evidence', models.TextField(blank=True)),
                ('normalized_name', models.CharField(blank=True, max_length=500)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_candidates', to='catalog.episodeguestextraction')),
            ],
            options={
                'ordering': ['-confidence', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='episodeguestextraction',
            constraint=models.UniqueConstraint(fields=('episode', 'prompt_version', 'model'), name='unique_episode_guest_extraction_model_prompt'),
        ),
    ]
