# Generated by Django 5.2.13 on 2026-05-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_person_normalized_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='enclosure_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.URLField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='website_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
