# Generated by Django 5.2.13 on 2026-05-12 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_episode_enclosure_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastHostExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=20)),
                ('prompt_version', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('input_text', models.TextField()),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extraction_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast_host_extractions', to='catalog.extractionrun')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_extractions', to='catalog.podcast')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('kind', models.CharField(choices=[('host', 'Host'), ('cohost', 'Co-host')], max_length=20)),
                ('confidence', models.FloatField(default=0)),
                ('evidence', models.TextField(blank=True)),
                ('normalized_name', models.CharField(blank=True, max_length=500)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_candidates', to='catalog.podcasthostextraction')),
            ],
            options={
                'ordering': ['kind', '-confidence', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='podcasthostextraction',
            constraint=models.UniqueConstraint(fields=('podcast', 'prompt_version', 'model'), name='unique_podcast_host_extraction_model_prompt'),
        ),
    ]
