# Generated by Django 5.2.13 on 2026-05-12 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_podcasthostextraction_hostcandidate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonObservation',
            fields=[
                ('observation_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('appearance', 'Appearance')], default='appearance', max_length=50)),
                ('record_id', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('host', 'Host'), ('guest', 'Guest')], max_length=20)),
                ('observed_name', models.CharField(max_length=500)),
                ('normalized_name', models.CharField(max_length=500)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('confidence', models.FloatField(default=1.0)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appearance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person_observation', to='catalog.appearance')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_observations', to='catalog.episode')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='catalog.person')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_observations', to='catalog.podcast')),
            ],
            options={
                'ordering': ['normalized_name', 'observation_id'],
            },
        ),
        migrations.CreateModel(
            name='CanonicalPersonEntity',
            fields=[
                ('am_entity_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=500)),
                ('normalized_name', models.CharField(max_length=500, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('roles', models.JSONField(blank=True, default=list)),
                ('observation_count', models.PositiveIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_method', models.CharField(default='exact_normalized_name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['normalized_name'], name='catalog_can_normali_6c06a8_idx'), models.Index(fields=['display_name'], name='catalog_can_display_b578f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='PersonEntityLink',
            fields=[
                ('observation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='entity_link', serialize=False, to='catalog.personobservation')),
                ('match_method', models.CharField(max_length=100)),
                ('match_probability', models.FloatField(default=1.0)),
                ('dbt_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canonical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_observations', to='catalog.canonicalpersonentity')),
            ],
        ),
        migrations.AddIndex(
            model_name='personobservation',
            index=models.Index(fields=['record_id'], name='catalog_per_record__47d5f4_idx'),
        ),
        migrations.AddIndex(
            model_name='personobservation',
            index=models.Index(fields=['normalized_name', 'role'], name='catalog_per_normali_73d2b2_idx'),
        ),
        migrations.AddIndex(
            model_name='personobservation',
            index=models.Index(fields=['podcast', 'role'], name='catalog_per_podcast_726540_idx'),
        ),
        migrations.AddIndex(
            model_name='personentitylink',
            index=models.Index(fields=['canonical'], name='catalog_per_canonic_a11785_idx'),
        ),
        migrations.AddIndex(
            model_name='personentitylink',
            index=models.Index(fields=['match_method'], name='catalog_per_match_m_7c2378_idx'),
        ),
        migrations.AddIndex(
            model_name='personentitylink',
            index=models.Index(fields=['dbt_updated_at'], name='catalog_per_dbt_upd_9fa54e_idx'),
        ),
    ]
