# Generated by Django 5.2.13 on 2026-05-12 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_personobservation_canonicalpersonentity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonEntityCandidatePair',
            fields=[
                ('pair_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('blocking_keys', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('match_probability', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='candidate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_candidate_pairs', to='catalog.canonicalpersonentity')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_candidate_pairs', to='catalog.canonicalpersonentity')),
            ],
            options={
                'ordering': ['-match_probability', 'left_id', 'right_id'],
                'indexes': [models.Index(fields=['status'], name='catalog_per_status_40dee5_idx'), models.Index(fields=['match_probability'], name='catalog_per_match_p_2a99ac_idx')],
                'constraints': [models.UniqueConstraint(fields=('left', 'right'), name='unique_person_entity_candidate_pair'), models.CheckConstraint(condition=models.Q(('left__lt', models.F('right'))), name='person_entity_candidate_pair_ordered')],
            },
        ),
    ]
