# Generated by Django 5.2.13 on 2026-05-12 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_personentitycandidatepair'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonEntityPairLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('match', 'Match'), ('not_match', 'Not match'), ('skip', 'Skip')], max_length=20)),
                ('source', models.CharField(default='human_active_learning', max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('match_probability', models.FloatField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='catalog.personentitycandidatepair')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['label'], name='catalog_per_label_8743f0_idx'), models.Index(fields=['source'], name='catalog_per_source_8254e0_idx'), models.Index(fields=['created_at'], name='catalog_per_created_bf17d0_idx')],
            },
        ),
    ]
