# Generated by Django 5.2.13 on 2026-05-12 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_personentitypairlabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='personentitypairlabel',
            name='pair_id_snapshot',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='personentitypairlabel',
            name='pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labels', to='catalog.personentitycandidatepair'),
        ),
    ]
