# Generated by Django 5.2.13 on 2026-05-12 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_personentitypairlabel_pair_id_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkMetricRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=20)),
                ('graph_version', models.CharField(default='network-metrics-v1', max_length=50)),
                ('person_nodes', models.PositiveIntegerField(default=0)),
                ('person_edges', models.PositiveIntegerField(default=0)),
                ('podcast_nodes', models.PositiveIntegerField(default=0)),
                ('podcast_edges', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonNetworkMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=500)),
                ('pagerank', models.FloatField(default=0.0)),
                ('hub', models.FloatField(default=0.0)),
                ('authority', models.FloatField(default=0.0)),
                ('closeness', models.FloatField(default=0.0)),
                ('betweenness', models.FloatField(default=0.0)),
                ('degree_centrality', models.FloatField(default=0.0)),
                ('pagerank_rank', models.PositiveIntegerField(default=0)),
                ('hub_rank', models.PositiveIntegerField(default=0)),
                ('authority_rank', models.PositiveIntegerField(default=0)),
                ('closeness_rank', models.PositiveIntegerField(default=0)),
                ('betweenness_rank', models.PositiveIntegerField(default=0)),
                ('degree_rank', models.PositiveIntegerField(default=0)),
                ('guest_appearances', models.PositiveIntegerField(default=0)),
                ('host_appearances', models.PositiveIntegerField(default=0)),
                ('podcast_count', models.PositiveIntegerField(default=0)),
                ('latest_episode_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canonical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_metrics', to='catalog.canonicalpersonentity')),
                ('representative_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='represented_network_metrics', to='catalog.person')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_metrics', to='catalog.networkmetricrun')),
            ],
            options={
                'ordering': ['pagerank_rank', 'display_name'],
                'indexes': [models.Index(fields=['run', 'pagerank_rank'], name='catalog_per_run_id_b6e870_idx'), models.Index(fields=['run', 'hub_rank'], name='catalog_per_run_id_b7cae2_idx'), models.Index(fields=['run', 'authority_rank'], name='catalog_per_run_id_c407d3_idx'), models.Index(fields=['run', 'closeness_rank'], name='catalog_per_run_id_be978d_idx'), models.Index(fields=['run', 'betweenness_rank'], name='catalog_per_run_id_dc3e47_idx'), models.Index(fields=['run', 'degree_rank'], name='catalog_per_run_id_aa0dd1_idx'), models.Index(fields=['canonical'], name='catalog_per_canonic_510d58_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'canonical'), name='unique_person_network_metric_per_run')],
            },
        ),
        migrations.CreateModel(
            name='PodcastNetworkMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closeness', models.FloatField(default=0.0)),
                ('betweenness', models.FloatField(default=0.0)),
                ('degree_centrality', models.FloatField(default=0.0)),
                ('closeness_rank', models.PositiveIntegerField(default=0)),
                ('betweenness_rank', models.PositiveIntegerField(default=0)),
                ('degree_rank', models.PositiveIntegerField(default=0)),
                ('shared_guest_edges', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_metrics', to='catalog.podcast')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast_metrics', to='catalog.networkmetricrun')),
            ],
            options={
                'ordering': ['degree_rank', 'podcast__name'],
                'indexes': [models.Index(fields=['run', 'closeness_rank'], name='catalog_pod_run_id_b6118c_idx'), models.Index(fields=['run', 'betweenness_rank'], name='catalog_pod_run_id_a4de61_idx'), models.Index(fields=['run', 'degree_rank'], name='catalog_pod_run_id_32dbfc_idx'), models.Index(fields=['podcast'], name='catalog_pod_podcast_73fb26_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'podcast'), name='unique_podcast_network_metric_per_run')],
            },
        ),
    ]
