# Generated by Django 5.2.13 on 2026-05-13 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_networkmetricrun_personnetworkmetric_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkEvolutionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='running', max_length=20)),
                ('graph_version', models.CharField(default='network-evolution-v1', max_length=50)),
                ('weeks_requested', models.PositiveIntegerField(default=0)),
                ('weeks_calculated', models.PositiveIntegerField(default=0)),
                ('start_week', models.DateField(blank=True, null=True)),
                ('end_week', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkEvolutionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('cutoff_at', models.DateTimeField()),
                ('person_nodes', models.PositiveIntegerField(default=0)),
                ('person_edges', models.PositiveIntegerField(default=0)),
                ('podcast_count', models.PositiveIntegerField(default=0)),
                ('guest_appearance_count', models.PositiveIntegerField(default=0)),
                ('largest_component_nodes', models.PositiveIntegerField(default=0)),
                ('largest_component_edges', models.PositiveIntegerField(default=0)),
                ('density', models.FloatField(default=0.0)),
                ('average_clustering', models.FloatField(default=0.0)),
                ('transitivity', models.FloatField(default=0.0)),
                ('average_shortest_path_length', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='catalog.networkevolutionrun')),
            ],
            options={
                'ordering': ['week_start'],
            },
        ),
        migrations.CreateModel(
            name='PersonNetworkEvolutionMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=500)),
                ('pagerank', models.FloatField(default=0.0)),
                ('hub', models.FloatField(default=0.0)),
                ('authority', models.FloatField(default=0.0)),
                ('closeness', models.FloatField(default=0.0)),
                ('pagerank_rank', models.PositiveIntegerField(default=0)),
                ('hub_rank', models.PositiveIntegerField(default=0)),
                ('authority_rank', models.PositiveIntegerField(default=0)),
                ('closeness_rank', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canonical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_evolution_metrics', to='catalog.canonicalpersonentity')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_metrics', to='catalog.networkevolutionsnapshot')),
            ],
            options={
                'ordering': ['snapshot__week_start', 'pagerank_rank', 'display_name'],
            },
        ),
        migrations.AddIndex(
            model_name='networkevolutionsnapshot',
            index=models.Index(fields=['week_start'], name='catalog_net_week_st_b47d72_idx'),
        ),
        migrations.AddIndex(
            model_name='networkevolutionsnapshot',
            index=models.Index(fields=['run', 'week_start'], name='catalog_net_run_id_f17730_idx'),
        ),
        migrations.AddConstraint(
            model_name='networkevolutionsnapshot',
            constraint=models.UniqueConstraint(fields=('week_start',), name='unique_network_evolution_snapshot_week'),
        ),
        migrations.AddIndex(
            model_name='personnetworkevolutionmetric',
            index=models.Index(fields=['canonical', 'snapshot'], name='catalog_per_canonic_e0a697_idx'),
        ),
        migrations.AddIndex(
            model_name='personnetworkevolutionmetric',
            index=models.Index(fields=['snapshot', 'pagerank_rank'], name='catalog_per_snapsho_7a3216_idx'),
        ),
        migrations.AddIndex(
            model_name='personnetworkevolutionmetric',
            index=models.Index(fields=['snapshot', 'hub_rank'], name='catalog_per_snapsho_2628f8_idx'),
        ),
        migrations.AddIndex(
            model_name='personnetworkevolutionmetric',
            index=models.Index(fields=['snapshot', 'authority_rank'], name='catalog_per_snapsho_562ffb_idx'),
        ),
        migrations.AddIndex(
            model_name='personnetworkevolutionmetric',
            index=models.Index(fields=['snapshot', 'closeness_rank'], name='catalog_per_snapsho_1f1e4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='personnetworkevolutionmetric',
            constraint=models.UniqueConstraint(fields=('snapshot', 'canonical'), name='unique_person_network_evolution_metric_per_snapshot'),
        ),
    ]
