# Generated by Django 5.2.13 on 2026-05-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_podcast_active_interview_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="networkevolutionsnapshot",
            name="episode_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkevolutionsnapshot",
            name="new_person_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkevolutionsnapshot",
            name="new_person_edge_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="networkevolutionsnapshot",
            name="new_podcast_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="personnetworkevolutionmetric",
            name="betweenness",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="personnetworkevolutionmetric",
            name="betweenness_rank",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="personnetworkevolutionmetric",
            name="degree_centrality",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="personnetworkevolutionmetric",
            name="degree_rank",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="personnetworkevolutionmetric",
            name="guest_appearances",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="personnetworkevolutionmetric",
            name="host_appearances",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="personnetworkevolutionmetric",
            name="latest_episode_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personnetworkevolutionmetric",
            name="podcast_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="personnetworkevolutionmetric",
            index=models.Index(
                fields=["snapshot", "betweenness_rank"], name="catalog_per_snapsho_8d03a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personnetworkevolutionmetric",
            index=models.Index(
                fields=["snapshot", "degree_rank"], name="catalog_per_snapsho_341ac2_idx"
            ),
        ),
    ]
