# Generated by Django 5.2.13 on 2026-05-23 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_extend_network_evolution_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureLinkPredictionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=120, unique=True)),
                ('cutoff_at', models.DateTimeField()),
                ('model_path', models.CharField(blank=True, max_length=1000)),
                ('gcs_model_uri', models.CharField(blank=True, max_length=1000)),
                ('model_type', models.CharField(blank=True, max_length=100)),
                ('feature_names', models.JSONField(blank=True, default=list)),
                ('score_histogram', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('scored_podcast_count', models.PositiveIntegerField(default=0)),
                ('rows_written', models.PositiveIntegerField(default=0)),
                ('max_degree', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-cutoff_at', '-created_at'],
                'indexes': [models.Index(fields=['cutoff_at'], name='catalog_fut_cutoff__6f6d6f_idx'), models.Index(fields=['created_at'], name='catalog_fut_created_003037_idx')],
            },
        ),
        migrations.CreateModel(
            name='FutureLinkWeeklyAuditRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=120, unique=True)),
                ('week_start', models.DateTimeField()),
                ('week_end', models.DateTimeField()),
                ('window_days', models.PositiveIntegerField(default=7)),
                ('model_path', models.CharField(blank=True, max_length=1000)),
                ('gcs_model_uri', models.CharField(blank=True, max_length=1000)),
                ('model_type', models.CharField(blank=True, max_length=100)),
                ('feature_names', models.JSONField(blank=True, default=list)),
                ('score_histogram', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('published_pair_count', models.PositiveIntegerField(default=0)),
                ('repeat_pair_excluded_count', models.PositiveIntegerField(default=0)),
                ('new_link_count', models.PositiveIntegerField(default=0)),
                ('scored_link_count', models.PositiveIntegerField(default=0)),
                ('candidate_eligible_count', models.PositiveIntegerField(default=0)),
                ('max_degree', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-week_end', '-created_at'],
                'indexes': [models.Index(fields=['week_end'], name='catalog_fut_week_en_d14c3f_idx'), models.Index(fields=['created_at'], name='catalog_fut_created_31c97b_idx')],
            },
        ),
        migrations.CreateModel(
            name='FutureLinkPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('score', models.FloatField()),
                ('distance', models.PositiveIntegerField()),
                ('features', models.JSONField(blank=True, default=dict)),
                ('canonical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.canonicalpersonentity')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.podcast')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='catalog.futurelinkpredictionrun')),
            ],
            options={
                'ordering': ['run', 'rank'],
                'indexes': [models.Index(fields=['run', 'rank'], name='catalog_fut_run_id_b7a186_idx'), models.Index(fields=['run', 'score'], name='catalog_fut_run_id_fa64b7_idx'), models.Index(fields=['podcast'], name='catalog_fut_podcast_9e3569_idx'), models.Index(fields=['canonical'], name='catalog_fut_canonic_0e4826_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'podcast', 'canonical'), name='unique_future_link_prediction_pair_per_run')],
            },
        ),
        migrations.CreateModel(
            name='FutureLinkWeeklyAuditLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('link_published_at', models.DateTimeField()),
                ('first_episode_published_at', models.DateTimeField()),
                ('latest_episode_published_at', models.DateTimeField()),
                ('distance', models.PositiveIntegerField(blank=True, null=True)),
                ('candidate_eligible', models.BooleanField(default=False)),
                ('was_existing_before_cutoff', models.BooleanField(default=False)),
                ('was_host_before_cutoff', models.BooleanField(default=False)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('canonical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.canonicalpersonentity')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.podcast')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='catalog.futurelinkweeklyauditrun')),
            ],
            options={
                'ordering': ['run', 'rank', '-link_published_at'],
                'indexes': [models.Index(fields=['run', 'rank'], name='catalog_fut_run_id_096810_idx'), models.Index(fields=['run', 'score'], name='catalog_fut_run_id_42b328_idx'), models.Index(fields=['link_published_at'], name='catalog_fut_link_pu_135c69_idx'), models.Index(fields=['podcast'], name='catalog_fut_podcast_b00735_idx'), models.Index(fields=['canonical'], name='catalog_fut_canonic_8cd2ae_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'podcast', 'canonical'), name='unique_future_link_weekly_audit_pair_per_run')],
            },
        ),
    ]
