# Generated by Django 5.2.13 on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_futurelinkpredictionrun_futurelinkweeklyauditrun_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scraperun",
            name="run_label",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
