# Generated by Codex on 2026-05-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_scraperun_run_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_label", models.CharField(max_length=120, unique=True)),
                ("phase", models.CharField(db_index=True, default="all", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("options", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PipelineStepRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=200)),
                ("command", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("elapsed_seconds", models.FloatField(blank=True, null=True)),
                ("options", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="catalog.pipelinerun",
                    ),
                ),
            ],
            options={
                "ordering": ["pipeline_run", "sequence"],
            },
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(fields=["run_label"], name="catalog_pip_run_lab_665ba8_idx"),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["status", "started_at"],
                name="catalog_pip_status_67e87d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinesteprun",
            index=models.Index(
                fields=["pipeline_run", "status"],
                name="catalog_pip_pipelin_ba3364_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinesteprun",
            index=models.Index(
                fields=["command", "status"],
                name="catalog_pip_command_54526f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="pipelinesteprun",
            constraint=models.UniqueConstraint(
                fields=("pipeline_run", "sequence"),
                name="unique_pipeline_step_sequence_per_run",
            ),
        ),
    ]
